site_name: Test readthedocs
site_description: 'A readthedocs test of mkdocs material'
site_author: 'Tyson Lee Swetnam'
docs_dir: docs/
repo_name: 'tyson-swetnam/mkdocs-reathedocs-template'
repo_url: 'https://github.com/tyson-swetnam/mkdocs-readthedocs-template'
nav:
    - Home: index.md
theme:
  name: 'material'
