docs_dir: docs/
repo_name: 'tyson-swetnam/mkdocs-readthedocs-template'
repo_url: 'https://github.com/tyson-swetnam/mkdocs-readthedocs-template'

site_name: 'CyVerse Learning Center'
site_description: 'Documentation for CyVerse Platforms and Education'
site_author: 'CyVerse Science Team'
site_url: https://tyson-swetnam.github.io/learning-materials-home-mkdocs/

edit_uri: edit/main/docs

# Copyright
copyright: 'Copyright &copy; 2022 CyVerse'

# Navigation Page
nav:
  - Home: index.md
  - Quick Start Guides: quick_starts.md
  - Platform Guides: platform_guides.md
  - Power Users: power_users.md
  - Tools and Apps: tools_and_apps.md
  - Tutorials: tutorials.md 
  - Webinars: webinars.md
  - Workshops: workshops.md
  - Contributing: contributing.md

# Reset theme to readthedocs
theme:
  name: material
  
# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
