site_name: Test readthedocs
site_description: 'A readthedocs test of mkdocs material'
site_author: 'Tyson Lee Swetnam'
docs_dir: docs/
repo_name: 'tyson-swetnam/mkdocs-readthedocs-template'
repo_url: 'https://github.com/tyson-swetnam/mkdocs-readthedocs-template'

# Navigation Page
nav:
    - Home: index.md

# Reset theme to readthedocs
theme:
  name: readthedocs
